version: '3.2'

services:

  news_aggregator_app: &app
    tty: true
    build:
      context: .
      args:
        requirements: requirements/development.txt
    container_name: news_aggregator
    environment:
      # use in code
      - DEBUG=True
      - SETTINGS_FILE=api.dev.yml
      - PYTHONUNBUFFERED=1
    restart: always
    volumes:
      - .:/app:delegated
    depends_on:
      - postgres
      - redis
    ports:
      - 8080:8080
      - 8081:8081
    command: make adev

  postgres:
      image: postgres:10
      container_name: news_aggregator_postgres
      environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
          - POSTGRES_DB=postgres
      ports:
          - 5432

  redis:
    image: redis:4
    ports:
        - 6379

  test:
    <<: *app
    container_name: news_aggregator_test
    ports:
      - 8082:8082
    command: make _test
